services:
  backend:
    image: 'flaviokov/jfood-api:1.0'
    environment:
      - 'DB_URL=jdbc:postgresql://postgres:5432/jfood'
      - 'DB_PASS=jfood'
      - 'DB_USER=jfood'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=jfood'
      - 'POSTGRES_PASSWORD=jfood'
      - 'POSTGRES_USER=jfood'
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'jfood@jfood.com'
      PGADMIN_DEFAULT_PASSWORD: 'jfood'