server:
  port: 8080

spring:
  application:
    name: jfood-api
  datasource:
    url: jdbc:postgresql://localhost:5432/jfood
    password: jfood
    username: jfood
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    open-in-view: false
    show-sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

